CREATE TABLE users (
	email VARCHAR(256) NOT NULL PRIMARY KEY,
	password VARCHAR(64) NOT NULL
);

CREATE TABLE savednpcs (
	id INTEGER(32) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	characterstring VARCHAR(8192) NOT NULL,
	owner VARCHAR(256)
);